name: build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and test
      uses: ./.github/actions/build-and-test