name: pages

on:
  push:
    branches:
      - docs-mkdocs

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and test
      uses: ./.github/actions/build-and-test
  build-docs:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download docgen exe
        uses: actions/download-artifact@v4
        with:
          name: docgen-exe
          path: docgen-exe
      - name: Run docgen exe
        run: ./docgen-exe/XlBlocks.AddIn.DocGen.exe
      - name : Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: pip install mkdocs-material
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build site
        run: mkdocs build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
